project:
  type: website
  output-dir: docs

website:
  title: "The Defence Economist"
  navbar:
    right:
      - text: Data 
        href: https://defenceeconomist.shinyapps.io/data
      - text: Knowledge 
        href: https://defenceeconomist.shinyapps.io/knowledge
      - icon: github
        href: https://github.com/lajh87
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

