---
title: "Notes on Economics of Defence - Chapter 7 (Procurement)"
description: "Notes on Chapter 7 Procurement, Theories and Evidence from Sandler and Hartley's economics of defence"
author: "Luke Heley"
date: "27 Dec 23"
freeze: true
execute:
  eval: true
format:
  html:
    toc: true
    code-fold: show
categories:
 - knowledge of economics
 - defence
 - notes
editor_options:
  chunk_output_type: console
---


# Introduction

The chapter reviews literature on defence contracts and competitive procurement, exploring various contract types and the decision-making processes in defence equipment acquisition.
The complexity of contracting involves transaction costs related to acquiring information, organizing competitions, bargaining, and enforcing contracts.
The government, as a buyer or principal, must specify requirements and ensure that contractors pursue the principal's goals.
Contracts that cannot detail all buyer requirements may lead to discretionary behaviour by contractors, influenced by their preferences.
Monitoring and enforcing contracts require measurable outputs, and incentives and penalties in contracts impact the behaviour of agents.
The chapter reviews traditional approaches to defence contracting, cost-estimating relationships, and various contract types, including recent theoretical developments.
Focus is given to market features, agent behaviour, and responses to contractual incentives and regulatory constraints.

# 2.1 Market Failure

Defence equipment markets function similarly to other markets by connecting buyers (defence ministries and armed forces) with sellers (defence industries).
The demand for defence equipment comes from national defence ministries, armed forces, and overseas governments, while defence industries, both nationally and internationally, supply the equipment.
The interaction between demand and supply is formalized through legally binding contracts, where buyers commit to paying a specified price for a product delivered on time.
Governments, acting as buyers, may impose regulatory requirements on contractors, such as profit controls, adding a layer of oversight.
The text introduces Figure 5.1, illustrating the market situation with a UK example.
Despite similarities, defence equipment markets have unique characteristics, including the central role of governments, cost trends, technical progress, cost curves, and regulatory aspects.
The government's role is crucial in determining technical progress, choosing equipment, and deciding whether to import or buy domestically.
Cost trends indicate that defence equipment, especially high-tech items, tends to become costlier over time.
Technical progress is a distinctive feature, leading to new products and markets, but also resulting in a smaller number of large firms dominating high-tech sectors.
Cost curves show that production costs of defence equipment increase over time, leading to downward pressures on the size and structure of armed forces.
Regulation plays a significant role in defence markets, with governments determining market openness, monitoring costs, and regulating profits on defence contracts.
The text refers to previous work by Peck and Scherer in 1963, highlighting the enduring relevance of these considerations in defence equipment markets.

_Government Influence in Defence Markets and Policy Objectives._

As a monopsonist, the government determines technical progress by choosing equipment and decides whether to import or buy domestically.
Government influence extends to determining the size and composition of its domestic defence capabilities.
The choice of defence equipment, including combat aircraft, missiles, submarines, and tanks, impacts the industry's structure, entry and exit, prices, exports, and profits.
Some advocate for an interventionist approach, using defence procurement to support "key" technologies and back industry winners as part of national industrial policy.
Supporters of free markets, such as Austrian economists, criticize this interventionist stance, emphasizing the uncertainty of the future and the unintended consequences of government involvement.
Public choice analysis predicts potential government failures in efforts to improve economic performance.
The use of defence procurement as an instrument of industrial policy raises fundamental questions about the objectives of defence policy.
Questions arise regarding whether defence procurement aims at efficiently acquiring equipment for national defence or pursuing broader economic and social objectives, including protecting the national defence industrial base.

_Challenges of Rising Costs in Defence Equipment and Adaptive Procurement Policies._

High technology defence equipment is costly and experiencing rising costs in real terms.
Examples include the estimated $35 billion cost for fifteen American B2 stealth bombers and approximately $130 million per copy for the US F-22 advanced tactical fighter aircraft (1991-2 prices).
Despite increased costs, new equipment is more productive than previous generations.
Real unit production costs of defence equipment, including aircraft, helicopters, missiles, warships, and submarines, increase by about 10 percent per annum.
This cost trend implies a doubling in cost approximately every 7.25 years.
Defence budgets often fail to match these cost increases, leading to downward pressures on the size and structure of armed forces.
There is a need to reshape defence industries supplying the forces, evident in long-term trends like a one-ship navy and a one-aircraft air force.
Efforts are made to address these challenges through adaptive procurement policies, such as competition policy, aiming to postpone some of the adjustment effects associated with rising costs.

_Evolution of Defence Equipment Markets and the Impact of Technical Progress._

Technical progress is a distinctive feature of defence equipment markets.
Major advances, such as in jet engines, missiles, electronics, and helicopters, create new markets.
Firms must invest in new development and production facilities with a focus on research and development (R & D).
Since 1945, there's a long-term trend towards fewer, larger firms, seen through mergers and exits from the defence sector.
High technology sectors, like aerospace and avionics, often have one or a few large national suppliers, forming a monopoly or oligopoly.
This market structure deviates significantly from the economists' model of perfect competition.
Defence spending cuts in the USA, UK, and the EU during the 1990s contribute to exits from the industry and restructuring around fewer large defence contractors.
EU states may maintain competition by opening their national markets to foreign suppliers.

_Economies of Scale and Competitiveness in High Technology Defence Sectors._

Some defence industries, especially high-tech sectors, exhibit decreasing costs, emphasizing economies of scale.
A national market in such sectors may only support one firm, resembling a monopoly.
Quantity becomes a critical factor in determining unit costs and overall competitiveness.
Long production runs allow for spreading high fixed research and development (R & D) costs over a larger volume.
Scale and learning economies in production contribute to cost efficiency and competitiveness in high-tech defence sectors.

_Government Regulation and Profit Controls in Defence Markets._

Defence markets and industries are subject to government regulation.
Governments have the authority to determine whether national markets should be open or closed.
Monitoring costs and profit controls on defence contracts are common regulatory practices.
Profit controls aim to prevent excessive profits or losses on defence business and maintain a domestic industrial base.
Profit levels may not serve as a standard signalling mechanism for entry or exit due to regulatory constraints.
Profit-conscious firms may adapt by increasing expenditure on unregulated items, such as luxury offices, company cars, and hoarding scientists and engineers.
The Tisdell and Hartley (1981) reference provides further insights into microeconomic policy in this context.

# 2.2 Demand: procurement policy


# 2.3 Competition, firm behavior, bargaining, and contract types
# 2.4 Cost-estimating relationships
# 2.5 The new economics of defense procurement and contracting
# 2.6 Game theory and procurement
# 2.7 The Impact of Market Failure of Contracting
# 2.8 Regulation
# 2.9 Competition, contracts, and performance
# 2.10 Conclusion: the results of competition
